<?php

function tech_log_menu () {
  $items = array();
  // $items['shows-events/%/%/%/%/tech-log'] = array(
  //   'page callback' => 'tech_log_load',
  //   'access callback' => 'user_access',
  //   'access arguments' => array('manage tech logs'),
  //   'page arguments' => array(1, 2, 3, 4),
  // );
  return $items;
}

function tech_log_permission () {
  return array(
    'manage tech logs' => array(
      'title' => t('Manage tech logs'),
      'description' => t('View and manage tech logs for events at the Ark.'),
    ),
  );
}

function tech_log_load () {
  
}
