<?php

require_once dirname(__FILE__) . '/includes/sound_tech.users.inc';
require_once dirname(__FILE__) . '/includes/sound_tech.events.inc';

function sound_tech_menu () {
  $items = array();

  $items['admin/sound-tech/events/%/edit'] = array(
    'access arguments' => array('manage sound tech events'),
    'access callback' => 'user_access',
    'page arguments' => array(3),
    'page callback' => 'sound_tech_edit_event',
  );

  $items['admin/sound-tech/people/%'] = array(
    'access arguments' => array('manage sound tech user accounts'),
    'access callback' => 'user_access',
    'page arguments' => array(3),
    'page callback' => 'sound_tech_show_user',
  );
  $items['admin/sound-tech/people/add'] = array(
    'access arguments' => array('manage sound tech user accounts'),
    'access callback' => 'user_access',
    'page callback' => 'sound_tech_add_user',
    'title' => 'Add Sound Tech User',
  );
  $items['admin/sound-tech/people/%/edit'] = array(
    'access arguments' => array(3),
    'access callback' => 'sound_tech_edit_user_access',
    'page arguments' => array(3),
    'page callback' => 'sound_tech_edit_user',
    'title arguments' => array(3),
    'title callback' => 'sound_tech_edit_user_title',
  );
  return $items;
}

function sound_tech_permission () {
  return array(
    'view sound tech pages' => array(
      'title' => t('View sound tech pages'),
      'description' => t('View sound tech pages.'),
    ),
    'manage sound tech user accounts' => array(
      'title' => t('Manage sound tech user accounts'),
      'description' => t('Manage sound tech user accounts.'),
    ),
    'manage sound tech events' => array(
      'title' => t('Manage sound tech events'),
      'description' => t('Manage sound tech events.'),
    ),
  );
}

function sound_tech_custom_theme () {
  if (arg(0) === 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    if (isset($node->type) && ($node->type === 'sound_tech' || $node->type === 'sound_tech_page')) {
      return 'the_ark_admin';
    }
  }
}

function sound_tech_node_access ($node, $op, $account) { // deny anonymous or unauthorized access to sound tech content
  $type = is_string($node) ? $node : $node->type;
  if (($type === 'sound_tech' || $type === 'sound_tech_page') && $op === 'view') {
    global $user;
    if (isset($user->roles[3]) || isset($user->roles[4]) || isset($user->roles[5])) {
      return NODE_ACCESS_ALLOW;
    } else {
      return NODE_ACCESS_DENY;
    }
  }
  return NODE_ACCESS_IGNORE;
}
